export const ALCOHOL_LIST = [
  {
    id: 101,
    nameKO: "처음처럼",
    alcoholPercent: 16.5,
    calResult: 0,
    category: "소주",
    bottle: 360,
    mfg: "하이트진로",
    tastingNote: "대나무 숯 정제로 이슬같은 깨끗함",
    img: "",
  },
  {
    id: 102,
    nameKO: "진로",
    alcoholPercent: 16,
    calResult: 0,
    category: "소주",
    bottle: 360,
    mfg: "하이트진로",
    tastingNote:
      "제로슈거 및 알코올 도수 16도의 진로 오리지널 레시피를 완성하여 초깔끔하고 부드러운 목넘김을 한층 강화",
    img: "",
  },
  {
    id: 103,
    nameKO: "톡소다 석류",
    alcoholPercent: 5,
    calResult: 0,
    category: "리큐르",
    bottle: 360,
    mfg: "무학",
    tastingNote:
      "상큼한 과즙과 청량한 탄산이 어우러진 무학의 과일 리큐르 제품입니다. 라인업: 석류/블루베리/사과/파인애플/레몬/트로피칼",
    img: "",
  },
  {
    id: 104,
    nameKO: "별빛청하 스파클링",
    alcoholPercent: 7,
    calResult: 0,
    category: "청주",
    bottle: 295,
    mfg: "롯데칠성음료",
    tastingNote: "화이트 와인의 달콤함과 톡톡 튀는 탄산을 함께 머금은 알코올",
    img: "",
  },
  {
    id: 201,
    nameKO: "아사히 수퍼드라이",
    country: "일본",
    alcoholPercent: 5,
    calResult: 0,
    category: "페일 라거",
    volume: 500,
    where: "편의점",
    tastingNote:
      "마시는 순간 목 넘김에서 빠르게 느껴지는 맥주의 풍미와 마지막까지 느껴지는 깔끔한 맛",
    img: "",
  },
  {
    id: 202,
    nameKO: "버드 와이저",
    country: "미국",
    alcoholPercent: 5.4,
    calResult: 0,
    category: "라거",
    volume: 500,
    where: "편의점",
    tastingNote:
      "1876년 탄생한 아메리칸 스타일의 프리미엄 라거. 오랜 발효 시간과 공을 들인 양조 과정으로 특유의 부드러운 목넘김이 특징",
    img: "",
  },
  {
    id: 203,
    nameKO: "필스너 우르켈",
    country: "체코",
    alcoholPercent: 4.4,
    calResult: 0,
    category: "페일 라거",
    volume: 500,
    where: "편의점",
    tastingNote: "상쾌하고 풍부하며 적절한 양의 호피 쓴맛",
    img: "",
  },
  {
    id: 204,
    nameKO: "카스 프레시",
    country: "한국",
    alcoholPercent: 4.5,
    calResult: 0,
    category: "라거",
    volume: 500,
    where: "편의점",
    tastingNote:
      "콜드브루 공법을 통해 맥주의 상쾌함과 깔끔한 맛을 한층 더 극대화한 톡 쏘고 상쾌한 맛",
    img: "",
  },
  {
    id: 205,
    nameKO: "테라",
    country: "한국",
    alcoholPercent: 4.6,
    calResult: 0,
    category: "라거",
    volume: 500,
    where: "편의점",
    tastingNote:
      "세계 공기질 부문 1위 호주에서 자란 청정맥아와 오직 발효공정에서 나오는 리얼탄산을 100% 사용하여 거품은 조밀하고 탄산은 오래 지속",
    img: "",
  },
  {
    id: 206,
    nameKO: "클라우드",
    country: "한국",
    alcoholPercent: 5,
    calResult: 0,
    category: "라거",
    volume: 500,
    where: "편의점",
    tastingNote:
      "100% 발효원액에 추가로 물을 타지 않은 오리지널 그래비티 공법으로 만들어 맛이 깊고 풍부한 맥주",
    img: "",
  },
  {
    id: 301,
    nameKO: "두르뜨, 그랑 떼루아",
    category: "소테른",
    title: "Dourthe, Grands Terroirs Sauternes",
    country: "프랑스",
    type: "white",
    alcoholPercent: 13.5,
    calResult: 0,
    bottle: 750,
    sweet: 5,
    acid: 3,
    body: 4,
    tannin: 1,
    aroma: "살구, 자몽, 꿀",
    tastingNote:
      "진한 노란색을 띠며 살구나 자몽 등 농익은 과일향과 아카시아 꽃, 꿀향이 피어오른다. 입 아네서는 진한 풍미화 함께 적절한 산도가 조화를 이루는 달콤한 디저트 와인이다.",
    img: "",
  },
  {
    id: 302,
    nameKO: "덕혼",
    category: "디코이 샤도네이",
    Name: "Duckhorn, Decoy Chardonnay",
    country: "미국",
    type: "white",
    alcoholPercent: 14,
    calResult: 0,
    bottle: 750,
    sweet: 1,
    acid: 3,
    body: 4,
    tannin: 1,
    aroma: "사과, 자몽, 아카시아, 미네랄",
    tastingNote:
      "푸른 사과와 자몽, 아카시아의 사랑스러운 향을 가지고 있다. 이에 더불어 젖은 돌 느낌의 미네랄 풍미가 생생한 산도와 어우러져 와인의 품격을 한층 높여준다.",
    img: "",
  },
  {
    id: 303,
    nameKO: "브레드&버터",
    category: "피노 누아",
    title: "Bread&Butter, Pinot Noir",
    country: "미국",
    type: "red",
    alcoholPercent: 14,
    calResult: 0,
    bottle: 750,
    sweet: 2,
    acid: 3,
    body: 4,
    tannin: 2,
    aroma: "라즈베리, 체리, 카시스, 오크",
    tastingNote:
      "선명한 루비색을 띠며 입 안에서는 달콤한 잘익은 베리류의 풍미가 감칠맛과 함께 입안 전체를 감돌며 부드러운 타닌과 함께 길게 이어지는 와인이다.",
    img: "",
  },
  {
    id: 304,
    nameKO: "카스텔라레",
    category: "키안티 클라시코",
    title: "Castellare, Chianti Classico",
    country: "이탈리아",
    type: "red",
    alcoholPercent: 13.5,
    calResult: 0,
    bottle: 750,
    sweet: 1,
    acid: 4,
    body: 4,
    tannin: 3,
    aroma: "체리",
    tastingNote:
      "윤기가 흐르는 가넷의 붉은 빛을 띠고 붉은 딸기류 과일향이 진하고 향기롭다. 집약된 과실의 맛이 느껴지며, 부드러운 탄닌의 매끄러운 질감과 균형 잡힌 구조감을 지닌 와인이다.",
    img: "",
  },
];
